export const GET_MOVIES_PENDING = "GET_MOVIES_PENDING";
export const GET_MOVIES_RESOLVED = "GET_MOVIES_RESOLVED";
export const GET_MOVIES_REJECTED = "GET_MOVIES_REJECTED";
export const URL_MOVIE = "http://subdomain.entony.fs.a-level.com.ua/api/movie";

export const GET_MOVIES_FILTER_PENDING = "GET_MOVIES_FILTER_PENDING";
export const GET_MOVIES_FILTER_RESOLVED = "GET_MOVIES_FILTER_RESOLVED";
export const GET_MOVIES_FILTER_REJECTED = "GET_MOVIES_FILTER_REJECTED";

export const GET_CHOOSE_MOVIE_RESOLVED = "GET_CHOOSE_MOVIE_RESOLVED";
export const GET_CHOOSE_MOVIE_DEFAULT_RESOLVED = "GET_CHOOSE_MOVIE_DEFAULT_RESOLVED";

export const GET_MOVIES_SPACE_SHADOW_PENDING = "GET_MOVIES_SPACE_SHADOW_PENDING";
export const GET_MOVIES_SPACE_SHADOW_RESOLVED = "GET_MOVIES_SPACE_SHADOW_RESOLVED";
export const GET_MOVIES_SPACE_SHADOW_REJECTED = "GET_MOVIES_SPACE_SHADOW_REJECTED";
export const URL_MOVIE_SPACE_SHADOW = "http://subdomain.entony.fs.a-level.com.ua/api/movie/space-shadow";
export const GET_MOVIES_ROOM_PENDING = "GET_MOVIES_ROOM_PENDING";
export const GET_MOVIES_ROOM_RESOLVED = "GET_MOVIES_ROOM_RESOLVED";
export const GET_MOVIES_ROOM_REJECTED = "GET_MOVIES_ROOM_REJECTED";
export const URL_MOVIE_ROOM = "http://subdomain.entony.fs.a-level.com.ua/api/movie/room";
export const GET_MOVIES_SESSION_PENDING = "GET_MOVIES_SESSION_PENDING";
export const GET_MOVIES_SESSION_RESOLVED = "GET_MOVIES_SESSION_RESOLVED";
export const GET_MOVIES_SESSION_REJECTED = "GET_MOVIES_SESSION_REJECTED";
export const URL_MOVIE_SESSION = "http://subdomain.entony.fs.a-level.com.ua/api/movie/session";
export const GET_MOVIES_SPACE_PENDING = "GET_MOVIES_SPACE_PENDING";
export const GET_MOVIES_SPACE_RESOLVED = "GET_MOVIES_SPACE_RESOLVED";
export const GET_MOVIES_SPACE_REJECTED = "GET_MOVIES_SPACE_REJECTED";
export const URL_MOVIE_SPACE = "http://subdomain.entony.fs.a-level.com.ua/api/movie/space";
